<?xml version="1.0" encoding="utf-8"?><Database Name="EC1_eStore" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=STEPHENSCAL4C56\SQLEXPRESS;Initial Catalog=EC1_eStore;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="EC1_eStoreConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="productID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="productName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="productDescription" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="unitPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="imageURL" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CategoryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>